<template>
  <section class="demo-section">
    <h2>🖥️ {{ locale === 'zh-CN' ? '后端验证演示' : 'Backend Verification' }}<span class="new-badge">服务端生成</span></h2>

    <div class="info-box">
      💡 {{ locale === 'zh-CN' ? '图片由后端服务生成，更安全可靠。需要先启动后端服务：cd server/node && pnpm dev' : 'Images generated by backend server for better security. Start server: cd server/node && pnpm dev' }}
    </div>

    <div class="options">
      <div class="option-row">
        <label>{{ locale === 'zh-CN' ? '服务地址' : 'Server URL' }}:</label>
        <input type="text" v-model="backendUrl" style="width: 200px;">
      </div>
      <div class="option-row">
        <label>{{ locale === 'zh-CN' ? '验证码类型' : 'Type' }}:</label>
        <select v-model="backendType">
          <option value="slider">{{ locale === 'zh-CN' ? '滑块验证' : 'Slider' }}</option>
          <option value="click">{{ locale === 'zh-CN' ? '点击验证' : 'Click' }}</option>
        </select>
      </div>
    </div>

    <div class="captcha-box">
      <SliderCaptcha
        v-if="backendType === 'slider'"
        ref="backendRef"
        :width="320"
        :height="180"
        verify-mode="backend"
        :backend-verify="{ getCaptcha: backendUrl + '/api/captcha?type=slider', verify: backendUrl + '/api/captcha/verify' }"
        :locale="locale"
        @success="onSuccess"
        @fail="onFail"
      />
      <ClickCaptcha
        v-else
        ref="backendRef"
        :width="320"
        :height="180"
        verify-mode="backend"
        :backend-verify="{ getCaptcha: backendUrl + '/api/captcha?type=click', verify: backendUrl + '/api/captcha/verify' }"
        :locale="locale"
        @success="onSuccess"
        @fail="onFail"
      />
    </div>

    <div class="btn-group">
      <button class="btn btn-secondary" @click="checkHealth">{{ locale === 'zh-CN' ? '检查服务状态' : 'Check Server' }}</button>
    </div>

    <h3 style="margin-top: 30px; margin-bottom: 15px;">{{ locale === 'zh-CN' ? '后端验证弹窗' : 'Backend Popup' }}</h3>

    <div class="options">
      <div class="option-row">
        <label>{{ locale === 'zh-CN' ? '验证码类型' : 'Type' }}:</label>
        <select v-model="popupType">
          <option value="slider">{{ locale === 'zh-CN' ? '滑块验证' : 'Slider' }}</option>
          <option value="click">{{ locale === 'zh-CN' ? '点击验证' : 'Click' }}</option>
        </select>
      </div>
      <div class="option-row">
        <label>{{ locale === 'zh-CN' ? '自动关闭' : 'Auto Close' }}:</label>
        <input type="checkbox" v-model="popupAutoClose">
      </div>
    </div>

    <div class="btn-group" style="margin-bottom: 20px;">
      <button class="btn btn-primary" @click="showPopup">{{ locale === 'zh-CN' ? '打开后端验证弹窗' : 'Open Backend Popup' }}</button>
    </div>

    <PopupCaptcha
      ref="popupRef"
      :key="popupType"
      :type="popupType"
      :auto-close="popupAutoClose"
      :captcha-options="{ width: 320, height: 180, locale, verifyMode: 'backend', backendVerify: { getCaptcha: backendUrl + '/api/captcha?type=' + popupType, verify: backendUrl + '/api/captcha/verify' } }"
      @success="() => console.log('Backend popup success')"
    />
  </section>
</template>

<script>
import { SliderCaptcha, ClickCaptcha, PopupCaptcha } from '@captcha/vue2'

export default {
  name: 'BackendDemo',
  components: { SliderCaptcha, ClickCaptcha, PopupCaptcha },
  props: {
    locale: { type: String, default: 'zh-CN' }
  },
  data() {
    return {
      backendUrl: 'http://localhost:3001',
      backendType: 'slider',
      popupType: 'slider',
      popupAutoClose: true
    }
  },
  methods: {
    async checkHealth() {
      try {
        const res = await fetch(this.backendUrl + '/api/health')
        const data = await res.json()
        alert((this.locale === 'zh-CN' ? '后端服务正常' : 'Backend service is healthy') + '\n\n' + JSON.stringify(data, null, 2))
      } catch {
        alert(this.locale === 'zh-CN' ? '无法连接后端服务' : 'Cannot connect to backend')
      }
    },
    onSuccess() {
      console.log('Backend captcha success:', this.$refs.backendRef?.getData())
    },
    onFail() {
      console.log('Backend captcha failed')
    },
    showPopup() {
      this.$refs.popupRef?.show()
    }
  }
}
</script>
