import {
	ClickCaptcha,
	createClickCaptcha,
	createInvisibleCaptcha,
	createPopupCaptcha,
	createSliderCaptcha,
	detectBrowserLocale,
	getLocale,
	getMessages,
	InvisibleCaptcha,
	PopupCaptcha,
	setLocale,
	SliderCaptcha,
	t,
	version,
} from './index'

export {
	ClickCaptcha,
	createClickCaptcha,
	createInvisibleCaptcha,
	createPopupCaptcha,
	createSliderCaptcha,
	detectBrowserLocale,
	getLocale,
	getMessages,
	InvisibleCaptcha,
	PopupCaptcha,
	setLocale,
	SliderCaptcha,
	t,
	version,
}

export default {
	ClickCaptcha,
	createClickCaptcha,
	createInvisibleCaptcha,
	createPopupCaptcha,
	createSliderCaptcha,
	detectBrowserLocale,
	getLocale,
	getMessages,
	InvisibleCaptcha,
	PopupCaptcha,
	setLocale,
	SliderCaptcha,
	t,
	version,
}
