import type { ReactElement, RefObject } from 'react'
import { ClickCaptcha, type ClickCaptchaInstance, PopupCaptcha, type PopupCaptchaInstance, SliderCaptcha, type SliderCaptchaInstance } from '@captcha-pro/react'
import { useRef, useState } from 'react'
import { useLocale } from '../hooks/useLocale'

export function BackendDemo(): ReactElement {
  const { currentLocale, t } = useLocale()
  const [backendUrl, setBackendUrl] = useState('http://localhost:3001')
  const [backendType, setBackendType] = useState<'slider' | 'click'>('slider')
  const [popupType, setPopupType] = useState<'slider' | 'click'>('slider')
  const [popupAutoClose, setPopupAutoClose] = useState(true)
  const backendRef = useRef<SliderCaptchaInstance | ClickCaptchaInstance>(null)
  const popupRef = useRef<PopupCaptchaInstance>(null)

  const checkHealth = async (): Promise<void> => {
    try {
      const res = await fetch(`${backendUrl}/api/health`)
      const data = await res.json()
      // eslint-disable-next-line no-alert
      alert(`${t('后端服务正常', 'Backend service is healthy')}\n\n${JSON.stringify(data, null, 2)}`)
    } catch {
      // eslint-disable-next-line no-alert
      alert(t('无法连接后端服务', 'Cannot connect to backend'))
    }
  }

  const CaptchaComponent = backendType === 'slider' ? SliderCaptcha : ClickCaptcha

  return (
    <section class="demo-section">
      <h2>
        🖥️
        {t('后端验证演示', 'Backend Verification')}
        <span class="new-badge">服务端生成</span>
      </h2>

      <div class="info-box">
        💡
        {' '}
        {t('图片由后端服务生成，更安全可靠。需要先启动后端服务：cd server/node && pnpm dev', 'Images generated by backend server. Start server: cd server/node && pnpm dev')}
      </div>

      <div class="options">
        <div class="option-row">
          <label>
            {t('服务地址', 'Server URL')}
            :
          </label>
          <input type="text" value={backendUrl} onChange={e => setBackendUrl(e.target.value)} style={{ width: '200px' }} />
        </div>
        <div class="option-row">
          <label>
            {t('验证码类型', 'Type')}
            :
          </label>
          <select value={backendType} onChange={e => setBackendType(e.target.value as 'slider' | 'click')}>
            <option value="slider">{t('滑块验证', 'Slider')}</option>
            <option value="click">{t('点击验证', 'Click')}</option>
          </select>
        </div>
      </div>

      <div class="captcha-box">
        <CaptchaComponent
          key={backendType}
          ref={backendRef as RefObject<SliderCaptchaInstance & ClickCaptchaInstance>}
          width={320}
          height={180}
          verifyMode="backend"
          backendVerify={{
            getCaptcha: `${backendUrl}/api/captcha?type=${backendType}`,
            verify: `${backendUrl}/api/captcha/verify`,
          }}
          locale={currentLocale}
          onSuccess={() => { /* Backend success */ }}
          onFail={() => { /* Backend fail */ }}
        />
      </div>

      <div class="btn-group">
        <button class="btn btn-secondary" onClick={checkHealth}>
          {t('检查服务状态', 'Check Server')}
        </button>
      </div>

      <h3 style={{ "margin-top": '30px', "margin-bottom": '15px' }}>{t('后端验证弹窗', 'Backend Popup')}</h3>

      <div class="options">
        <div class="option-row">
          <label>
            {t('验证码类型', 'Type')}
            :
          </label>
          <select value={popupType} onChange={e => setPopupType(e.target.value as 'slider' | 'click')}>
            <option value="slider">{t('滑块验证', 'Slider')}</option>
            <option value="click">{t('点击验证', 'Click')}</option>
          </select>
        </div>
        <div class="option-row">
          <label>
            {t('自动关闭', 'Auto Close')}
            :
          </label>
          <input type="checkbox" checked={popupAutoClose} onChange={e => setPopupAutoClose(e.target.checked)} />
        </div>
      </div>

      <div class="btn-group" style={{ "margin-bottom": '20px' }}>
        <button class="btn btn-primary" onClick={() => popupRef.current?.show()}>
          {t('打开后端验证弹窗', 'Open Backend Popup')}
        </button>
      </div>

      <PopupCaptcha
        key={popupType}
        ref={popupRef}
        type={popupType}
        autoClose={popupAutoClose}
        captchaOptions={{
          width: 320,
          height: 180,
          locale: currentLocale,
          verifyMode: 'backend',
          backendVerify: {
            getCaptcha: `${backendUrl}/api/captcha?type=${popupType}`,
            verify: `${backendUrl}/api/captcha/verify`,
          },
        }}
        onSuccess={() => { /* Backend popup success */ }}
      >
        <span />
      </PopupCaptcha>
    </section>
  )
}
