<script setup lang="ts">
import { ref } from 'vue'
import { SliderCaptcha, ClickCaptcha, PopupCaptcha, type CaptchaStatistics } from '@captcha/vue3'
import { useLocale } from '../composables/useLocale'

const { currentLocale, t } = useLocale()

const backendUrl = ref('http://localhost:3001')
const config = ref({ type: 'slider' as 'slider' | 'click' })
const captchaRef = ref()
const stats = ref<CaptchaStatistics | null>(null)

const popupConfig = ref({
  type: 'slider' as 'slider' | 'click',
  autoClose: true
})
const popupRef = ref()

const checkBackendHealth = async () => {
  try {
    const res = await fetch(`${backendUrl.value}/api/health`)
    const data = await res.json()
    alert(t('后端服务正常', 'Backend service is healthy') + `\n\n${JSON.stringify(data, null, 2)}`)
  } catch {
    alert(t('无法连接后端服务，请确保已启动服务端:\ncd server/node && pnpm dev', 'Cannot connect to backend. Please start the server:\ncd server/node && pnpm dev'))
  }
}

const getData = () => {
  const data = captchaRef.value?.getData()
  console.log('Backend captcha data:', data)
  alert(t('验证数据已输出到控制台', 'Data logged to console'))
}

const updateStats = () => {
  const s = captchaRef.value?.getStatistics()
  if (s) stats.value = s
}

const showPopup = () => popupRef.value?.show()
</script>

<template>
  <section class="demo-section">
    <h2>🖥️ {{ currentLocale === 'zh-CN' ? '后端验证演示' : 'Backend Verification' }}<span class="new-badge">服务端生成</span></h2>

    <div class="info-box">
      💡 {{ currentLocale === 'zh-CN'
        ? '图片由后端服务生成，更安全可靠。需要先启动后端服务：cd server/node && pnpm dev'
        : 'Images generated by backend server for better security. Start server: cd server/node && pnpm dev' }}
    </div>

    <div class="options">
      <div class="option-row">
        <label>{{ currentLocale === 'zh-CN' ? '服务地址' : 'Server URL' }}:</label>
        <input type="text" v-model="backendUrl" style="width: 200px;">
      </div>
      <div class="option-row">
        <label>{{ currentLocale === 'zh-CN' ? '验证码类型' : 'Type' }}:</label>
        <select v-model="config.type">
          <option value="slider">{{ currentLocale === 'zh-CN' ? '滑块验证' : 'Slider' }}</option>
          <option value="click">{{ currentLocale === 'zh-CN' ? '点击验证' : 'Click' }}</option>
        </select>
      </div>
    </div>

    <div class="captcha-box">
      <SliderCaptcha
        v-if="config.type === 'slider'"
        ref="captchaRef"
        :width="320"
        :height="180"
        verify-mode="backend"
        :backend-verify="{
          getCaptcha: `${backendUrl}/api/captcha?type=slider`,
          verify: `${backendUrl}/api/captcha/verify`
        }"
        :locale="currentLocale"
        @success="() => { console.log('Backend slider success'); updateStats() }"
        @fail="() => console.log('Backend slider fail')"
      />
      <ClickCaptcha
        v-else
        ref="captchaRef"
        :width="320"
        :height="180"
        verify-mode="backend"
        :backend-verify="{
          getCaptcha: `${backendUrl}/api/captcha?type=click`,
          verify: `${backendUrl}/api/captcha/verify`
        }"
        :locale="currentLocale"
        @success="() => { console.log('Backend click success'); updateStats() }"
        @fail="() => console.log('Backend click fail')"
      />
    </div>

    <div class="btn-group">
      <button class="btn btn-secondary" @click="checkBackendHealth">{{ currentLocale === 'zh-CN' ? '检查服务状态' : 'Check Server' }}</button>
      <button class="btn btn-secondary" @click="getData">{{ currentLocale === 'zh-CN' ? '获取数据' : 'Get Data' }}</button>
    </div>

    <!-- 后端弹窗验证 -->
    <h3 style="margin-top: 30px; margin-bottom: 15px;">{{ currentLocale === 'zh-CN' ? '后端验证弹窗' : 'Backend Popup' }}</h3>

    <div class="options">
      <div class="option-row">
        <label>{{ currentLocale === 'zh-CN' ? '验证码类型' : 'Type' }}:</label>
        <select v-model="popupConfig.type">
          <option value="slider">{{ currentLocale === 'zh-CN' ? '滑块验证' : 'Slider' }}</option>
          <option value="click">{{ currentLocale === 'zh-CN' ? '点击验证' : 'Click' }}</option>
        </select>
      </div>
      <div class="option-row">
        <label>{{ currentLocale === 'zh-CN' ? '自动关闭' : 'Auto Close' }}:</label>
        <input type="checkbox" v-model="popupConfig.autoClose">
      </div>
    </div>

    <div class="btn-group" style="margin-bottom: 20px;">
      <button class="btn btn-primary" @click="showPopup">{{ currentLocale === 'zh-CN' ? '打开后端验证弹窗' : 'Open Backend Popup' }}</button>
    </div>

    <PopupCaptcha
      ref="popupRef"
      :key="popupConfig.type"
      :type="popupConfig.type"
      :auto-close="popupConfig.autoClose"
      :captcha-options="{
        width: 320,
        height: 180,
        locale: currentLocale,
        verifyMode: 'backend',
        backendVerify: {
          getCaptcha: `${backendUrl}/api/captcha?type=${popupConfig.type}`,
          verify: `${backendUrl}/api/captcha/verify`
        }
      }"
      @success="() => console.log('Backend popup success')"
    />
  </section>
</template>
